// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-KmvukuPlaxyulARNeo27-1RfgGjsv4',
    appId: '1:1006842867636:android:b2d866cf7901d448010ce1',
    messagingSenderId: '1006842867636',
    projectId: 'aura-508612',
    storageBucket: 'aura-508612.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_M1HC-NS3PX5KTZOICX_yU6KgBWoBzg',
    appId: '1:1006842867636:ios:c0d08a05d9d58693010ce1',
    messagingSenderId: '1006842867636',
    projectId: 'aura-508612',
    storageBucket: 'aura-508612.firebasestorage.app',
    androidClientId: '1006842867636-v2io5qcqsf7srqbobfcea3p97qrjnddg.apps.googleusercontent.com',
    iosClientId: '1006842867636-ukiq1f0970h94uenmsif48i3n3l9lii4.apps.googleusercontent.com',
    iosBundleId: 'com.aura.app.aura',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_M1HC-NS3PX5KTZOICX_yU6KgBWoBzg',
    appId: '1:1006842867636:ios:c0d08a05d9d58693010ce1',
    messagingSenderId: '1006842867636',
    projectId: 'aura-508612',
    storageBucket: 'aura-508612.firebasestorage.app',
    androidClientId: '1006842867636-v2io5qcqsf7srqbobfcea3p97qrjnddg.apps.googleusercontent.com',
    iosClientId: '1006842867636-ukiq1f0970h94uenmsif48i3n3l9lii4.apps.googleusercontent.com',
    iosBundleId: 'com.aura.app.aura',
  );
}
